services:
  db:
    image: docker.io/postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data:z
      - ./share:/share:z
